Repository paw-lu/dressup, pull requests merged in 2020-05, with the labels that each got.

#22 Translator class
  src/dressup/converter.py
  tests/test_converter.py
Labels: refactoring

#29 Fix backslash character not being properly escaped
  poetry.lock
  pyproject.toml
  src/dressup/translator.toml
Labels: bug

#35 Table
  mypy.ini
  poetry.lock
  pyproject.toml
  src/dressup/console.py
  tests/test_console.py
Labels: enhancement

#37 Release 0.1.1
  pyproject.toml
Labels: documentation
